/**:
  ros__parameters:
    # point painting range
    point_cloud_range: [-1000000.0, -1000000.0, -10000.0, 10000.0,10000.0, 0.0]
    # subscribe_topic_name
    segmentation_topic : /segmentationinfo
    camera_info_topic : /wamv/sensors/cameras/ball_shooter_camera_sensor/optical/camera_info
    point_cloud_topic : /wamv/sensors/lidars/lidar_wamv_sensor/points
    #debug_mode
    debug : true