/**:
  ros__parameters:
    # point painting range
    point_cloud_range: [-76.8, -76.8, -3.0, 76.8, 76.8, 5.0]
    # subscribe_topic_name
    segmentation_topic : /SegmentationInfo
    camera_info_topic : /wamv/sensors/cameras/ball_shooter_camera_sensor/camera_info
    point_cloud_topic : /wamv/sensors/lidars/lidar_wamv_sensor/points
    #debug_mode
    debug : true