/**:
  ros__parameters:
    # point painting range
    point_cloud_range: [-720.0, -720.0, -100.0, 720.0,720.0, 100.0]
    min_area_matrix : [-100.0,100.0]
    max_area_matrix : [-100.0,100.0]
    # subscribe_topic_name
    segmentation_topic : /detic_onnx_ros2_node/detic_result/segmentation_info 
    camera_info_topic : /wamv/sensors/cameras/ball_shooter_camera_sensor/camera_info 
    point_cloud_topic : /wamv/sensors/lidars/lidar_wamv_sensor/points
    #debug_mode
    debug : false