/**:
  ros__parameters:
    class_names: ["RED_BUOY","YELLO_BUOY","BLOCK_BUOY","DOCK"] 
    point_cloud_range: [-76.8, -76.8, -3.0, 76.8, 76.8, 5.0]
    min_area_matrix : [30,90]
    max_area_matrix : [30,90]